version: '3.4'

services:
  api:
    image: api:dev
    container_name: API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_api$
    volumes:
      - /Users/MAC/Documents/GitHub/sghartoon-app/backend/API:/app
      - /Users/MAC/Documents/GitHub/sghartoon-app/backend:/src
      - /Users/MAC/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_api$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_api$ \"/app/bin/Debug/net7.0/API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true