apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api
          image: ramibhs/backend:0b8ee14d466d189a7f67126f4e64f01b46423b9e
          ports:
            - containerPort: 80
