apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api
          image: ramibhs/backend:5350ddcb1a09cfaad1480e2dd18b768bfaaad9ca
          ports:
            - containerPort: 80
