apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api
          image: ramibhs/backend:0554b63f779bc3b8947a496ecd380b1d7af92b88
          ports:
            - containerPort: 80
