apiVersion: v1
kind: Service
metadata:
  name: dotnet-api-service
  namespace: argocd
spec:
  selector:
    app: dotnet-api
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  type: LoadBalancer
