apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sghartoon-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/ramibelhadjsalem/sghartoon-app.git'
      revision: HEAD
      directories:
      - path: 'k8s/backend'
      - path: 'k8s/front'
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/ramibelhadjsalem/sghartoon-app.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
