apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: ramibhs/frontend:2080843e62c939729bd39baca4cee5528b2de6c6
        ports:
        - containerPort: 80
