name: Backend CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Change directory to backend/API
      run: cd backend/API

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64 -t ramibhs/backend:${{ github.sha }}  .
        echo "DOCKER_IMAGE=ramibhs/backend:${{ github.sha }}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push ramibhs/backend:${{ github.sha }}
      
    - name: Display deployment.yaml before modification
      run: cat k8s/backend/deployment.yaml
      
    - name: Update image tag in deployment.yaml
      uses: OpsVerseIO/image-updater-action@0.1.0
      with:
        valueFile: 'k8s/backend/deployment.yaml'
        propertyPath: 'spec.template.spec.containers[0].image'
        value: ramibhs/backend:${{ github.sha }}
        commitChange: false
        branch: master
        targetBranch: master
        createPR: false
        message: 'Update deployment image to ramibhs/backend:${{ github.sha }}'
        token: ${{ secrets.TOKEN }}
        
    - name: Display deployment.yaml after modification
      run: cat k8s/backend/deployment.yaml

    - name: Send notification to Slack via webhook
      if: success()
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: 'general'
        payload: |
                {
                  "text": "Backend CI build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Backend CI build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                      }
                    }
                  ]
                }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack via webhook
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'general'
          payload: |
                  {
                    "text": "Backend CI pipeline result: ${{ needs.build.result }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "Backend CI pipeline result: ${{ needs.build.result }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                        }
                      }
                    ]
                  }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
